#!/usr/bin/env bash
set -e

echo "Applying grants on DB '${PIM_DB}' for role '${PIM_ADMIN}'..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PIM_DB" <<-EOSQL
  GRANT USAGE ON SCHEMA public TO ${PIM_ADMIN};

  GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public
  TO ${PIM_ADMIN};

  GRANT USAGE, SELECT, UPDATE
  ON ALL SEQUENCES IN SCHEMA public
  TO ${PIM_ADMIN};

  GRANT EXECUTE
  ON ALL FUNCTIONS IN SCHEMA public
  TO ${PIM_ADMIN};

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PIM_ADMIN};

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${PIM_ADMIN};

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO ${PIM_ADMIN};
EOSQL

echo "Grants applied."
